using System.Text.Json.Serialization;

using Rum.Core;

namespace Rum.Data;

public static partial class Errors
{
    /// <summary>
    /// an Error generated by a Rule for a
    /// Collection Index
    /// </summary>
    /// <param name="rule">the unique rule name/identifier</param>
    /// <param name="index">the index</param>
    /// <param name="message">the error message</param>
    public static IError Index(string rule, int index, string message)
    {
        return new IndexError(rule, index, message);
    }

    /// <summary>
    /// an Error generated by a Rule for a
    /// Collection Index
    /// </summary>
    /// <param name="rule">the unique rule name/identifier</param>
    /// <param name="index">the index</param>
    /// <param name="message">the error message</param>
    public class IndexError(string rule, int index, string message) : RuleError(rule, message), IError
    {
        /// <summary>
        /// the index of the element that the error
        /// relates to
        /// </summary>
        [JsonPropertyName("index")]
        [JsonPropertyOrder(0)]
        public int Index { get; } = index;
    }
}